export enum LanguageCodeEnums {
  ar_AE = "ar_AE",
  en_US = "en_US",
  cs_CZ = "cs_CZ",
  de_DE = "de_DE",
  el_GR = "el_GR",
  en_AU = "en_AU",
  en_GB = "en_GB",
  en_PH = "en_PH",
  en_SG = "en_SG",
  es_ES = "es_ES",
  es_MX = "es_MX",
  fr_FR = "fr_FR",
  hu_HU = "hu_HU",
  it_IT = "it_IT",
  ja_JP = "ja_JP",
  ko_KR = "ko_KR",
  pl_PL = "pl_PL",
  pt_BR = "pt_BR",
  ro_RO = "ro_RO",
  ru_RU = "ru_RU",
  th_TH = "th_TH",
  tr_TR = "tr_TR",
  vi_VN = "vi_VN",
  zh_CN = "zh_CN",
  zh_TW = "zh_TW",
}

export const LanguageCodeToLanguage: { [key in LanguageCodeEnums]: string } = {
  ar_AE: "العربية",
  en_US: "English (NA)",
  cs_CZ: "Čeština",
  de_DE: "Deutsch",
  el_GR: "Ελληνικά",
  en_AU: "English (OCE)",
  en_GB: "English (EUW)",
  en_PH: "English (PH)",
  en_SG: "English (SG)",
  es_ES: "Español (EUW)",
  es_MX: "Español (LATAM)",
  fr_FR: "Français",
  hu_HU: "Magyar",
  it_IT: "Italiano",
  ja_JP: "日本語",
  ko_KR: "한국어",
  pl_PL: "Polski",
  pt_BR: "Português",
  ro_RO: "Română",
  ru_RU: "Русский",
  th_TH: "ภาษาไทย",
  tr_TR: "Türkçe",
  vi_VN: "Tiếng Việt",
  zh_CN: "中文",
  zh_TW: "繁體中文",
};
